### ISSUE TITLE
Fix the auto-publish of the Casdoor docs site

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#1]

**Comment by hsluoyz** [comment]
@ErikQQY

**Comment by ErikQQY** [comment]
@hsluoyz Plz following [this github action guide](https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-) to generate ssh key and add the **private key** in ```Casdoor-website > Settings > Secrets```, and the **public key** in ```Casdoor.github.io > Settings > Deploy keys```
