### ISSUE TITLE
Integrate Crowdin to support online translation (i18n)

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#11]
Crowdin project created: https://crowdin.com/project/casdoor

@ErikQQY plz set it up.

**Comment by ErikQQY** [comment]
Working on it.

**Comment by hsluoyz** [comment]
@ErikQQY any update?

**Comment by ErikQQY** [comment]
The Crowdin integration is working: https://github.com/casdoor/casdoor-website/runs/2735334844

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-website/commit/4ff16d318bf629b4e2885c7d4d8eabce57167e48
