### ISSUE TITLE
Chinese translation update

### ISSUE THREAD

**Issue by Tim-Paik** [casdoor/casdoor-website#118]
The Chinese translation in [crowdin](https://crowdin.com/project/casdoor-website/zh-CN) has been 100%, waiting for an update

**Comment by hsluoyz** [comment]
Hi @Tim-Paik thanks for the contribution! Please use English in GitHub issues.

**Comment by hsluoyz** [comment]
@Tim-Paik also can you fix the wrong English text you mentioned in CrowdIn (by making PR in this repo)?
