### ISSUE TITLE
Hide the github corner in the demo iframes of the website

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#137]
Hide the corner when shown in iframe and make its height larger:

![image](https://user-images.githubusercontent.com/3787410/159045024-5258b446-f039-45e9-991e-7d42db3d7cb2.png)

Similar for other iframes.

**Comment by keithwym** [comment]
I think delete`<a href="https://github.com/casbin/casnode" class="github-corner" aria-label="Open GitHub project"><svg width="80" height="80" viewBox="0 0 250 250" style="position: absolute; top: 0px; fill: rgb(255, 255, 255); right: 0px;"><path class="octo-banner" d="M0 0l115 115h15l12 27 108 108V0z" fill="#151513"></path><path class="octo-arm" d="M128 109c-15-9-9-19-9-19 3-7 2-11 2-11-1-7 3-2 3-2 4 5 2 11 2 11-3 10 5 15 9 16" style="transform-origin: 130px 106px;"></path><path class="octo-body" d="M115 115s4 2 5 0l14-14c3-2 6-3 8-3-8-11-15-24 2-41 5-5 10-7 16-7 1-2 3-7 12-11 0 0 5 3 7 16 4 2 8 5 12 9s7 8 9 12c14 3 17 7 17 7-4 8-9 11-11 11 0 6-2 11-7 16-16 16-30 10-41 2 0 3-1 7-5 11l-12 11c-1 1 1 5 1 5z"></path></svg></a>`  will Hide the github corner.  
if  i edit this element  height will change iframes  `<iframe class="headerwindow" src="https://forum.casbin.com" width="870px" height="450px" border="0" frameborder="0"></iframe>`    make height bigger.

**Comment by hsluoyz** [comment]
@keithwym I know how to do this, what we need is the PR contribution. Also need to detect iframe.
