### ISSUE TITLE
Add a docs page to explain the password types and how to choose them

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#178]
See: https://door.casdoor.com/organizations/casbin , our users don't know how to choose them

![image](https://user-images.githubusercontent.com/3787410/163699740-8e1b094b-fcf0-433e-957f-b3b40633f35a.png)

The new page can be added to: https://casdoor.org/docs/overview

![image](https://user-images.githubusercontent.com/3787410/163699780-05d3be23-dcd7-4d19-bc0b-d911dcfe3e2c.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by Jenniline** [comment]
Hi, @hsluoyz  I have installed the casdoor-website locally and I have it running. 
I am learning how to create docs with it. I will like to work on this issue. 
Please assign this to me

Thank you

**Comment by Jenniline** [comment]
Hi @seriouszyx 
I didn't know this was an admin issue, I started working on this yesterday.

Please can I submit my Pull request on this issue just to show how I created the documentation?

Since potential contributors for GSOD'22 need to prove that they know how to create documentation

Thanks

**Comment by hsluoyz** [comment]
@Jenniline we are OK with anyone who first make a qualified PR. But for this issue, it seems that @seriouszyx already made one: https://github.com/casdoor/casdoor-website/pull/180 , so maybe can you choose another issue to work on?

**Comment by Jenniline** [comment]
Okay, @hsluoyz Thank you for notifying me.

I had already made the PR here is the link. 
I understand that the code might not be merged, but this is in an attempt to demonstrate my ability to write docs for the casbin and casdoor projects.

Please review and let me know of corrections I should take note of when working on other issues.

Thank you

**Comment by hsluoyz** [comment]
@Jenniline plz don't write too long for simple things. You can refer to: https://github.com/casdoor/casdoor-website/pull/180

**Comment by Jenniline** [comment]
Okay 
Thank you for the correction @hsluoyz 
I will take note of it as I work on the other docs
