### ISSUE TITLE
Add a docs page about connecting to Grafana with Casdoor via OAuth

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#187]
See how Grafana's OAuth works: https://grafana.com/docs/grafana/latest/auth/generic-oauth/

We may also need to add this to docs: https://casdoor.org/docs/integration/minio and fix any encountered bugs.

![image](https://user-images.githubusercontent.com/3787410/165453413-036bb68a-e7d8-429d-b06c-c895ec4985bb.png)

**Comment by rakuten** [comment]
@hsluoyz 
I can help add Grafana and JumpServer documents, but I can only provide Chinese content and need someone to translate it into English

By the way, I also use casdoor on [Gitea](https://gitea.io) and [Drone](https://www.drone.io)

**Comment by hsluoyz** [comment]
@rakuten ok, can you write Chinese blogs here: https://github.com/casbin/casbin-mp/tree/master/blogs  by making PR?
