### ISSUE TITLE
Describe userinfo and get-account APIs in docs

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#203]
Add https://github.com/casdoor/casdoor/pull/447 to https://casdoor.org/docs/how-to-connect/access_token#how-to-use-accesstoken

**Comment by Swastyy** [comment]
Hi @hsluoyz , Can I work on this issue?

**Comment by hsluoyz** [comment]
@Swastyy sure

**Comment by Swastyy** [comment]
Hi @hsluoyz, I am interested in participating in Google season of Docs for the Casdoor website, Can I still apply for it?

**Comment by hsluoyz** [comment]
@Swastyy plz see the official site
