### ISSUE TITLE
How to add custom script like Baidu Tongji?

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#21]
Baidu Tongji: https://tongji.baidu.com/

I added it to Casbin's Docusaurus v1 docs: https://github.com/casbin/casbin-website/commit/d6fd6f3963636487a3b8ecf8d7757503de320882

But I don't know how to do this for Docusaurus v2?

**Comment by ErikQQY** [comment]
I think we can follow the Docusaurus v2 docs https://docusaurus.io/docs/using-plugins#module-definition to add Baidu Tongji

**Comment by hsluoyz** [comment]
@ErikQQY OK. Can you make a PR to add the code?

```
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?<my code>";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
```

**Comment by ErikQQY** [comment]
OK, working on it
