### ISSUE TITLE
Could we have a comparison table for casdoor and keycloak?

### ISSUE THREAD

**Issue by billyhu** [casdoor/casdoor-website#237]
As some ones are familiar with keycloak and learning to use casdoor, it's better to know the differences on the same features.
here is an example for comparing opa and casbin - https://gist.github.com/StevenACoffman/1644ec1157a793eb7d868aa22b260e91

**Comment by RVShershnev** [comment]
Here you can find a comparison of Casdoor vs Keycloak vs Zitadel
https://habr.com/ru/articles/720490/

**Comment by hsluoyz** [comment]
@RVShershnev thanks

Closed here

**Comment by billyhu** [comment]
Thanks @RVShershnev , it's Great!
