### ISSUE TITLE
There is a doc that doesn't show up in the sidebar

### ISSUE THREAD

**Issue by Selflocking** [casdoor/casdoor-website#244]
https://casdoor.org/docs/events/overview
https://github.com/casdoor/casdoor-website/blob/master/docs/events/overview.md

We need to add it to the proper location.

**Comment by hsluoyz** [comment]
We can add it to the following place. Some contents of it are also needed to be improved, e.g., using offcial names like "Webhooks", add screenshots, etc.

![image](https://user-images.githubusercontent.com/3787410/178918854-5f624df9-7fe3-4e10-9fe9-ebe39e7a1603.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor-website/pull/247
