### ISSUE TITLE
Incorrect translation of Chinese documents

### ISSUE THREAD

**Issue by ziliangyu** [casdoor/casdoor-website#268]
link: https://casdoor.org/zh/docs/basic/core-concept
![KN8S`ZKX$KL$4YCLAC9IHKY](https://user-images.githubusercontent.com/53009950/182993167-9dcad207-70b4-4dc2-8f24-535a5132d293.png)

**Comment by hsluoyz** [comment]
@ziliangyu good found! Can you fix it at Crowdin? https://crowdin.com/project/casdoor-website

**Comment by ziliangyu** [comment]
> @ziliangyu good found! Can you fix it at Crowdin? https://crowdin.com/project/casdoor-website

yes. I hava fixed it.

**Comment by hsluoyz** [comment]
Thanks!
