### ISSUE TITLE
Add a Casdoor page to alist's docs

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#278]
For PR: https://github.com/alist-org/alist/pull/1453

Add a top-level page after: https://alist-doc.nn.ci/en/docs/setting/backend

![image](https://user-images.githubusercontent.com/3787410/183664557-0a8ea473-d697-497a-9d50-45dcffa57cbf.png)

**Comment by hsluoyz** [comment]
@wenxuan70

**Comment by wenxuan70** [comment]
PR: 
alist-org/alist-doc#31

**Comment by hsluoyz** [comment]
Done at: https://alist-doc.nn.ci/docs/setting/casdoor
