### ISSUE TITLE
Translate the docs to 100%

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#280]
Translate the language from 84% to 100%: https://crowdin.com/project/casdoor-website

![image](https://user-images.githubusercontent.com/3787410/183868776-9ec9449c-e814-42f8-b2b0-0cea3d5a4995.png)

**Comment by FoeverA0** [comment]
[WeOpen Star]I would like to help

**Comment by FoeverA0** [comment]
I have finished this task, please check:)

**Comment by hsluoyz** [comment]
good job, everyone! Done here

**Comment by reg4git** [comment]
done
![image](https://user-images.githubusercontent.com/99128194/188603736-ee480b02-3691-4d7f-a165-8bd898f494c9.png)

**Comment by hsluoyz** [comment]
Good!
