### ISSUE TITLE
"try-with-docker" docs has some wrong

### ISSUE THREAD

**Issue by Linvery** [casdoor/casdoor-website#321]
https://casdoor.org/docs/basic/try-with-docker
![image](https://user-images.githubusercontent.com/23356865/187677613-194edf6c-354e-4530-8c3e-9bb81995a55c.png)
Original: docker run  -p 8000:8000 -v /path/to/app.conf:/conf casbin/casdoor:latest
should be: docker run  -p 8000:8000 -v /path/to/:/conf casbin/casdoor:latest

example:
docker run  -p 8000:8000 -v /www/wwwroot/casdoor/conf:/conf casbin/casdoor:v1.105.0 (will be work)
docker run  -p 8000:8000 -v /www/wwwroot/casdoor/conf/app.conf:/conf casbin/casdoor:v1.105.0 (not work)
![image](https://user-images.githubusercontent.com/23356865/187678181-12ed0ca0-10d4-4534-8260-76b39315bf70.png)
![image](https://user-images.githubusercontent.com/23356865/187678236-cd555ab6-5c12-473f-8ddc-025397734185.png)

Finally, I suggest that the example should be modified as follows
docker run  -p 8000:8000 -v /www/wwwroot/casdoor/conf:/conf casbin/casdoor:v1.105.0

**Comment by Selflocking** [comment]
I think the documentation author thought /path/to/app.conf refers to the path to the parent folder of app.conf.
I took your suggestion into consideration, and there are a few points that I disagree with.
1. `casbin/casdoor:v1.105.0` We should use `casbin/casdoor:latest`.
2. `/www/wwwroot/casdoor/conf` It's not a general directory, we need to explain what this directory represents.

So I added a note(#324 ), how about this.

**Comment by Linvery** [comment]
> 我认为文档作者认为`/path/to/app.conf`是指 app.conf 的父文件夹的路径。 我考虑了你的建议，有几点我不同意。
> 
> 1. `casbin/casdoor:v1.105.0`我们应该使用`casbin/casdoor:latest`.
> 2. `/www/wwwroot/casdoor/conf`它不是一个通用目录，我们需要解释一下这个目录代表什么。
> 
> 所以我添加了一个注释（#324），这个怎么样。



I suggest changing “/path/to/ app.conf” to “/path/to/, because this is a command, which will be misunderstood by docker beginners.

docker run  -p 8000:8000 -v /path/to/:/conf casbin/casdoor:latest
The `/path/to/` refers to the path to the **folder** containing app.conf.
Anyway just **mount the app.conf to /conf/app.conf** and start it.

**Comment by Linvery** [comment]
> `/path/to/app.conf` means `the path to app.conf`. `/path/to/` is meaningless How about this:
> 
> ```shell
> docker run  -p 8000:8000 -v /path/to/conf/:/conf/ casbin/casdoor:latest
> ```

great! I agree with you !

**Comment by hsluoyz** [comment]
@Linvery @Selflocking I have a better idea:

1. In the docs, `/path/to/conf/` will be changed to `/folder/of/app.conf`, so no one will mistake it in docs.
2. Modify the Casdoor source code to handle both cases, either `/somefolder/app.conf` or `/somefolder` is supported. Implementing this is very simple: just try to remove the suffix `/app.conf`, if it exists, then it's removed, else nothing happens.

**Comment by Linvery** [comment]
> @Linvery @Selflocking I have a better idea:
> 
> 1. In the docs, `/path/to/conf/` will be changed to `/folder/of/app.conf`, so no one will mistake it in docs.
> 2. Modify the Casdoor source code to handle both cases, either `/somefolder/app.conf` or `/somefolder` is supported. Implementing this is very simple: just try to remove the suffix `/app.conf`, if it exists, then it's removed, else nothing happens.

I agree. But How to remove the suffix /app.conf ? This is a Linux Command , The error is generated from the docker , It seems that it is not an error from casdoor.

**Comment by hsluoyz** [comment]
@Linvery OK, I thought it was Go. Then only 1 would be fine
