### ISSUE TITLE
Make an initial version of docs for Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#4]
We need to add docs to: https://casdoor.org/ , first we need to move the README (https://github.com/casbin/casdoor) to the site.

For docs site structure, see Casbin as reference: https://casbin.org/docs/en/overview

![image](https://user-images.githubusercontent.com/3787410/120065014-cc9c6000-c0a1-11eb-91ed-f2263be74744.png)

**Comment by hsluoyz** [comment]
@ErikQQY @Kininaru

**Comment by Kininaru** [comment]
Got that, working on this.

**Comment by ErikQQY** [comment]
Got it.
