### ISSUE TITLE
bug: the pdf can not be opened

### ISSUE THREAD

**Issue by leo220yuyaodog** [casdoor/casdoor-website#401]
Both the Chinese and Engish pdf can not be opened. 

![image](https://user-images.githubusercontent.com/71440988/202952021-ba296f31-5ef4-43c3-b989-5efcac8402d4.png)

**Comment by Selflocking** [comment]
please try again: https://casdoor.org/pdf

**Comment by leo220yuyaodog** [comment]
> please try again: https://casdoor.org/pdf

Oh, that is right.  Thanks

**Comment by Selflocking** [comment]
> Both the Chinese and Engish pdf can not be opened.

This file is to prevent `broken link` errors when building. It is an empty file that will be replaced when the action runs successfully
