### ISSUE TITLE
Code block theme issue in homepage 

### ISSUE THREAD

**Issue by dewanshDT** [casdoor/casdoor-website#432]
### while the system default theme is dark the code block's theme stays in light mode hence resulting in contrast issue causing the text to be unreadable 
![casdoor](https://user-images.githubusercontent.com/71703033/215866714-5ed96994-87a7-4770-b2d4-489d9edb26a0.png)

### This problem goes away after toggling the theme from light to dark manually
![casdoorfix](https://user-images.githubusercontent.com/71703033/215866906-479ce9f3-1c29-47d1-b14d-63ca1de2e625.png)

**Comment by dewanshDT** [comment]
hey can I work on this?

**Comment by hsluoyz** [comment]
@dewanshDT ok

**Comment by dewanshDT** [comment]
hey we can close this as this was the issue from docusarus and I've reported it there
