### ISSUE TITLE
[docs] add dotnet avalonia example

### ISSUE THREAD

**Issue by RVShershnev** [casdoor/casdoor-website#539]
Dear maintainers,

I create repo for demo avaloniaUI. There are some differences from wpf.
https://github.com/RVShershnev/casdoor-dotnet-avalonia-example

You can add link from https://casdoor.org/docs/how-to-connect/desktop-sdks/dotnet-app

Thank you.

**Comment by hsluoyz** [comment]
@RVShershnev can you make a PR to add it?

**Comment by RVShershnev** [comment]
yes, #540

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-website/commit/ade2ed31ad7d1e6ea5f5860a16cf06e8ff8788dc
