### ISSUE TITLE
Create Route for index.yaml

### ISSUE THREAD

**Issue by sp71** [casdoor/casdoor-website#590]
Many applications surface their helm's index directly on their website. For example, [airflow](https://airflow.apache.org/index.yaml) surfaces its index.yaml as a top level route (notice the url). This allows the installation process to be smoother as users can just install helm chart using the website.

**Airflow Example**
helm repo add apache-airflow https://airflow.apache.org

The request is to surface the index.yaml on the website (https://casdoor.com/index.yaml). The route can just grab the index.yaml from [github](https://raw.githubusercontent.com/casdoor/casdoor-helm/master/charts/casdoor/index.yaml) as it's already available.

**Potential Casdoor Example**
helm repo add casdoor https://casdoor.com

**Comment by hsluoyz** [comment]
@sp71 can this be done at: https://casdoor.org/index.yaml ? I don't know if this is possible with Docusaurus but I guess probably OK. You can make PR to: https://github.com/casdoor/casdoor-website

**Comment by sp71** [comment]
Yeah that route would be perfect. I'm not familiar with Docusaurus unfortunately. I'm unsure how they go about surfacing just a file. It would need to be fetched from Github before surfacing though

**Comment by sp71** [comment]
Since helm is moving towards OCI registries over index yaml, we no longer need to support this
