### ISSUE TITLE
Better production documentation story

### ISSUE THREAD

**Issue by idc77** [casdoor/casdoor-website#636]
I'm trying to run casdoor with a production configuration.
The documentation is poor.

https://casdoor.org/docs/basic/server-installation/

For instance, DefaultStorageProvider, the linked page says it can be Local or Cloud, which values (case sensitive) represent which values?
Then
origin is the origin backend domain name.
What does that mean? Origin of what, localhost:8000? fqdn?

Frontendbasedir? "../casdoor" but it's under web when you git clone

Please add some proper documentation for production setups.

edit:
How to disable radius and ldap? Or how to make them listen on localhost only?

**Comment by hsluoyz** [comment]
It's better if you can contribute to this issue. It will be low priority on our side.

**Comment by idc77** [comment]
You're a funny guy. Should I pull the information out my ass?
