### ISSUE TITLE
Translate the SDKs Usage page

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-website#99]
See: https://casdoor.org/zh/docs/basic/SDKs

**Comment by hsluoyz** [comment]
@seriouszyx @Steve0x2a can anyone do this?

**Comment by seriouszyx** [comment]
I'll try to do it.

**Comment by seriouszyx** [comment]
Done https://crowdin.com/translate/casdoor/381/en-zhcn?filter=basic&value=0

**Comment by hsluoyz** [comment]
@seriouszyx great!
